---
language: python
services: docker

env:
  global:
    - ROLE_NAME: toolkit-dev
  matrix:
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604

install:
  - pip install molecule docker

before_script:
  - cd ../
  - mv ansible-$ROLE_NAME alvarobacelar.$ROLE_NAME
  - cd alvarobacelar.$ROLE_NAME

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
