---

- name: add key google chrome
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present

- name: add repo google chrom
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    state: present

- name: install google chrom
  apt:
    name: google-chrome-stable
    state: present
    update_cache: true
