---

- name: add key code
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: add repo code
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    state: present

- name: install code
  apt:
    name: code
    state: present
    update_cache: true
