---

- name: add repo kdenlive
  apt_repository:
    repo: 'ppa:kdenlive/kdenlive-stable'
    codename: bionic

- name: install kdenlive
  apt:
    name: kdenlive
    state: present
    update_cache: true
